### ISSUE TITLE
Sync slower than other node

### ISSUE THREAD

**Issue by 0xTH0R** [allada/bsc-archive-snapshot#23] opened 2022-07-06 06:48 UTC
I have run following your spec requirement on AWS EC2 on im4gn.2xlarge in us-west-2 apart from OS, i'm using Centos8 after configurated everything following your script and run for 3 days the node is sync to almost latest block but it always slower than other node around 500 - 1000 block is it normally for an archive node?

![image](https://user-images.githubusercontent.com/106047315/177486695-994760cf-a92a-425e-a8af-f2cad31e6d2a.png)

**Comment by allada** [comment] 2022-07-06 07:03
Sadly yes. I've been interacting a bit with the Erigon dev team on this issue, but nothing yet. The issue is with committing the state into mdbx. The only major thing they suggested that might help is change the db page size, but this requires a full resync. I'm doing it now, but will take another 30 days to finish.

**Comment by 0xTH0R** [comment] 2022-07-06 07:31
What page size did you use for that?

**Comment by 0xTH0R** [comment] 2022-07-08 12:27
@allada Thank, are there any tracking issues from erigon so we can track that this will be solve and close this issue.

**Comment by allada** [comment] 2022-07-09 08:10
Not that I know of. I talk to the team via discord about it. They are aware, but they haven't done really anything about it because there's so many features they are still working on.

I was told that they will eventually do some bench-marking and optimizing, but that will happen at sometime in the future (no eta)

**Comment by allada** [comment] 2022-08-30 20:47
This should be fixed with: https://github.com/allada/bsc-archive-snapshot/commit/4d8d56ac1fe424c119ef1925f387ce24df484e31

**Closed by allada** 2022-08-30 20:47 UTC
